config/routes.rb
Rails.application.routes.draw do
  get '/users/:id/change_password', to:'users#change_password', as:'change_password'
  patch '/users/:id/change_password', to:'users#update_password', as:'update_password'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update]

  resources :posts, shallow: true do
    resources :comments, only: [:create, :destroy]
  end

  get '/', to:'welcome#index', as:'home'
  get '/about_us', to:'welcome#about_us', as:'about_us'


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_admin?
        can :manage, :all
      else
        can :read, :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can(:manage, Post) do |post| #manage meaning this person is allowed to do everything on their own post
      user === post.user
    end

    can(:manage, Comment) do |comment|
      user === comment.user || user === comment.post.user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user 
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  has_many :comments, dependent: :destroy
  validates :title, presence: true, uniqueness: { message: 'Title must be unique' }
  validates :body, presence: true, length: { minimum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :nullify #even if user is deleted, the comments or posts remain
  has_many :posts, dependent: :nullify
  has_secure_password
  validates :first_name, :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,
    presence: true,
    uniqueness: true,
    format: VALID_EMAIL_REGEX

  #might be useful later since we don't have username option yet 
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?

  def current_user
    if session[:user_id].present?
      @_current_user ||= User.find_by(id: session[:user_id])
    end
  end

  helper_method :current_user #makes the current_user available to any view page 

  def authenticate_user!
    unless user_signed_in?
      flash[:alert] = "You must sign in our sign up first"
      redirect_to new_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment_params = params.require(:comment).permit(:body)
    @post = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.post = @post #this comment is referring to which post
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      @comments = @post.comments.order(created_at: :desc)
      render 'posts/show'
    end
  end

  def destroy
    comment = Comment.find params[:id]

    unless can?(:manage, comment)
      flash[:alert] = "Access Denied"
      redirect_to post_path(comment.post)
      return
    end
    comment.destroy
    redirect_to post_path(comment.post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def new
    # allows you to use the instance variable in the view
    @post = Post.new
    #by default will show the new.html.erb
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post) #@post.id technically, but this is the shortcut
    else
      render :new
    end
  end

  def edit
    # @post = Post.find params[:id] #need this variable so you can prepopulate your views/edit.html.erb page
  end

  def update
    if @post.update post_params
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def authorize_user!
    unless can?(:manage, @post)
      flash[:alert] = "Access Denied"
      redirect_to post_path(@post)
    end
  end

  def post_params
    post_params = params.require(:post).permit([:title, :body])
  end

  def find_post
    @post = Post.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:notice] = "Thanks for signing in"
      session[:user_id] = user.id
      redirect_to home_path
    else
      flash[:alert] = "Wrong e-mail or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now signed out"
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new #show a page to create a new user
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:notice] = "Thanks for signing up!"
      redirect_to home_path
    else #else stay on the same page
      render :new
    end
  end

  def edit #prepopulate it with user information
    @u = current_user
  end

  def update
    @u = current_user
    if @u.update user_params
      redirect_to edit_user_path(@u)
    else
      render :edit
    end
  end

  def change_password #just generating the view page
    @u = current_user
  end

  def update_password
    @u = current_user
    if @u.authenticate(params[:user][:current_password]) # method from bcrypt and has_secure_password
      @u.update user_params
      flash[:notice] = "Password changed!"
      redirect_to change_password_path 
    else
      flash[:alert] = "Wrong current password"
      redirect_to change_password_path
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :password, :password_confirmation
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about_us
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogglr</title>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="http://lh5.ggpht.com/hyT1S5pScNMReR3JAMYU1g-j8kxSitvoO-PVFtEDNPxiWS_e9cdduOakHveY_rYcJbc=w300"/>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- simple navbar -->
    <!-- <div>
    <%= link_to 'All', posts_path %>
    |
    <%= link_to 'Add New', new_post_path %>
    </div> -->

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" style="border-bottom:rgb(87, 98, 117) solid;border-width:2px">
      <a class="navbar-brand" href="/">
        <!-- <img src="http://lh5.ggpht.com/hyT1S5pScNMReR3JAMYU1g-j8kxSitvoO-PVFtEDNPxiWS_e9cdduOakHveY_rYcJbc=w300" style="height:50px;width:50px"/>   -->
        <%= image_tag "dogglr2.png", style:"height:50px;width:150px;" %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= about_us_path %>">About<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Posts<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_post_path %>">Add New</a>
          </li>

          <% if current_user.present?  %>
          <li class="nav-item">
            <%= link_to 'Account', edit_user_path(current_user), class:"nav-link", method:"get"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', session_path, class:"nav-link", method:"delete" %>
          </li>

          <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
          </li>
          <% end %>
        </ul>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="No action..." aria-label="Search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container-fluid">
      <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type == "alert" ? "danger" : "success" %> alert-dismissible fade show" role="alert">
        <%= msg %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 60rem;">
      <div class="card-body">
        <h1 class="card-title"><strong><%= @post.title %></strong></h1>
        <h6 class="card-subtitle mb-2 text-muted">Guess this post wasn't good enough for ya huh? Haha just kidding. Change whatever</h6>
        <hr>
        <!-- fancy form here -->
        <%= form_for @post do |f| %>

            <p class="form-errors">
              <%= @post.errors.full_messages.join(', ') %>
            </p>
            <div class="form-group">
              <strong><%= f.label :title, for:"input1" %></strong><br />
              <%= f.text_field :title, type:"text", class:"form-control", id:"input1" %>
            </div>

            <div class="form-group">
              <strong><%= f.label :body, 'Content', for:"textarea" %></strong><br />
              <%= f.text_area :body, placeholder:"What'chu thinking about?", class:"form-control", id:"textarea", rows:"4" %>
            </div>

            <%= f.submit "Save Changes", class:"btn btn-outline-dark" %>

        <% end %>
      </div>
    </div>
</div>

app/views/posts/index.html.erb
<h1 id="just_everything">Just. Everything.</h1>
<!-- <div>
  <% @posts.each do |post| %>
    <%= link_to post.title, post_path(post.id), class: "ml-3" %><br />
    <small class="ml-3 mt-3">Added <%= time_ago_in_words(post.created_at) %> ago</small>
    <hr>
  <% end  %>
</div> -->

<div class="mt-4" id="show_page">
<% @posts.each do |post| %>
  <div class="card ml-3 mb-3 mx-auto" style="width: 50rem;">
    <div class="card-body">
      <h5 class="card-title"><strong><%= link_to post.title, post_path(post.id), id:"index_title" %></strong></h5>

      <% if current_user == post.user %>
      <h6 class="card-subtitle mb-2 text-muted">Added <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.full_name, edit_user_path(current_user) %></h6>

      <% else %>
      <h6 class="card-subtitle mb-2 text-muted">Added <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.first_name %> <%= post.user.last_name %></h6>
      <% end %>

      <p class="card-text"><%= post.body %></p>
    </div>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 60rem;">
      <div class="card-body">
        <h1 class="card-title"><strong>Add Something!</strong></h1>
        <h6 class="card-subtitle mb-2 text-muted">Something fancy? Boring? A joke? You name it</h6>
        <hr>
        <!-- fancy form here -->
        <%= form_for @post do |f| %>

            <p class="form-errors">
              <%= @post.errors.full_messages.join(', ') %>
            </p>
            <div class="form-group">
              <strong><%= f.label :title, for:"input1" %></strong><br />
              <%= f.text_field :title, type:"text", class:"form-control", id:"input1" %>
            </div>

            <div class="form-group">
              <strong><%= f.label :body, 'Content', for:"textarea" %></strong><br />
              <%= f.text_area :body, placeholder:"What'chu thinking about?", class:"form-control", id:"textarea", rows:"4" %>
            </div>

            <%= f.submit "Submit", class:"btn btn-outline-dark" %>

        <% end %>
      </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 60rem;">
      <div class="card-body">
        <h1 class="card-title"><strong><%= @post.title %></strong></h1>

        <% if current_user == @post.user %>
          <h6 class="card-subtitle mb-2 text-muted">Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= link_to @post.user.full_name, edit_user_path(current_user)%></h6>
        <% else %>
          <h6 class="card-subtitle mb-2 text-muted">Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.first_name %> <%= @post.user.last_name %></h6>
        <% end %>

        <p class="card-text"><%= @post.body %></p>
        <hr>
        <% if user_signed_in? %>
            <small>
              <%= link_to "Edit", edit_post_path(@post.id) %>
              |
              <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Delete this post forever? And all the comments!!"}%>
            </small>
        <% end %>
      </div>
    </div>
</div>

<div class="mt-4">
  <div class="card ml-3 mb-3 mx-auto rounded" style="width: 60rem;">
      <div class="card-body">
        <h3><strong>New Comment</strong></h3>
        <!-- add a comment to database -->
        <%= form_for [@post, @comment] do |f| %>
          <p class="form-errors">
            <%= @comment.errors.full_messages.join(', ') %>
          </p>
          <div>
            <%= f.text_area :body, placeholder: "What's on your mind?", class:"form-control", id:"exampleFormControlTextarea1", cols: 60, rows: 4 %>
          </div>
          <%= f.submit "Submit", class:"btn btn-outline-dark mt-3" %>
        <% end %>
        <hr>
        <!-- Displaying all comments associated with the particular post -->

          <h3><strong>Comments</strong></h3>
          <ul class="comment-list">
            <% @comments.each do |comment| %>
            <hr>
            <li>
              <p><%= comment.body %><br />
                <small>

                  <% if current_user == comment.user %>
                    <strong><%= link_to comment.user.full_name, edit_user_path(current_user) %></strong> commented <%= time_ago_in_words(comment.created_at) %> ago
                  <% else %>
                    <strong><%= comment.user.first_name %> <%= comment.user.last_name %></strong> commented <%= time_ago_in_words(comment.created_at) %> ago
                  <% end %>

                </small>

                <% if user_signed_in? %>
                |
                <small>
                  <%= link_to "Delete", comment_path(comment),
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
                </small>
                <% end %>

              </p>
            </li>
            <% end %>
          </ul>
          <hr>


      </div>
  </div>
</div>

app/views/users/change_password.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 40rem;">
      <div class="card-body">
        <h1 class="card-title"><strong>Change Password</strong></h1>
        <hr>

      <!-- need error messages if the confirmations don't match -->

      <%= form_for(@u, url: update_password_path) do |f| %>
          <p class="form-errors">
            <%= @u.errors.full_messages.join(', ') %>
          </p>
          <div class="form-group">
            <strong><%= f.label :current_password, for:"input1" %></strong><br />
            <%= f.password_field :current_password, type:"password", class:"form-control", id:"input1" %>
          </div>
          <div class="form-group">
            <strong><%= f.label 'New Password', for:"input2" %></strong><br />
            <%= f.password_field :password, type:"password", class:"form-control", id:"input2" %>
          </div>
          <div class="form-group">
            <strong><%= f.label 'New Password Confirmation', for:"input3" %></strong><br />
            <%= f.password_field :password_confirmation, type:"password", class:"form-control", id:"input3" %>
          </div>

          <%= f.submit "Submit", class:"btn btn-outline-dark" %>

        <% end %>

      </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 40rem;">
      <div class="card-body">
        <h1 class="card-title"><strong>Account</strong></h1>
        <h6 class="card-subtitle mb-2 text-muted">Change whatever...</h6>
        <hr>

        <%= form_for @u do |f| %>

            <p class="form-errors">
              <%= @u.errors.full_messages.join(', ') %>
            </p>
            <div class="form-group">
              <strong><%= f.label :first_name, for:"input1" %></strong><br />
              <%= f.text_field :first_name, type:"text", class:"form-control", id:"input1" %>
            </div>
            <div class="form-group">
              <strong><%= f.label :last_name, for:"input2" %></strong><br />
              <%= f.text_field :last_name, type:"text", class:"form-control", id:"input2" %>
            </div>
            <div class="form-group">
              <strong><%= f.label :email, for:"input3" %></strong><br />
              <%= f.email_field :email, type:"text", class:"form-control", id:"input3" %>
            </div>

            <%= f.submit "Submit", class:"btn btn-outline-dark" %>

            <% end %>
            <hr>

            <div class="form-group">
              <strong><%= label_tag "Password" %></strong>: ************<br />

            </div>
            <%= link_to "Change Password", change_password_path, class:"btn btn-outline-dark" %>


      </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 40rem;">
      <div class="card-body">
        <h1 class="card-title"><strong>Sign Up</strong></h1>
        <h6 class="card-subtitle mb-2 text-muted">Just sign your life away</h6>
        <hr>

        <%= form_for @user do |f| %>

            <p class="form-errors">
              <%= @user.errors.full_messages.join(', ') %>
            </p>
            <div class="form-group">
              <strong><%= f.label :first_name, for:"input1" %></strong><br />
              <%= f.text_field :first_name, type:"text", class:"form-control", id:"input1" %>
            </div>
            <div class="form-group">
              <strong><%= f.label :last_name, for:"input2" %></strong><br />
              <%= f.text_field :last_name, type:"text", class:"form-control", id:"input2" %>
            </div>
            <div class="form-group">
              <strong><%= f.label :email, for:"input3" %></strong><br />
              <%= f.email_field :email, type:"text", class:"form-control", id:"input3" %>
            </div>
            <div class="form-group">
              <strong><%= f.label :password, for:"input4" %></strong><br />
              <%= f.password_field :password, type:"password", class:"form-control", id:"input4" %>
            </div>
            <div class="form-group">
              <strong><%= f.label :password_confirmation, for:"input5" %></strong><br />
              <%= f.password_field :password_confirmation, type:"password", class:"form-control", id:"input5" %>
            </div>

            <%= f.submit "Submit", class:"btn btn-outline-dark" %>

        <% end %>
      </div>
    </div>
</div>

app/views/welcome/about_us.html.erb
<div class="mt-4" id="show_page">
    <div class="card ml-3 mb-3 mx-auto rounded" style="width: 60rem;">
      <div class="card-body">
        <h1 class="card-title"><strong>About Us</strong></h1>
        <h6 class="card-subtitle mb-2 text-muted">Well there ain't all that much to know right now. It's a blogging website. You already know what that is. Real simple stuff.<br />Here's a majestic corgi:</h6>
        <hr>
        <%= image_tag "magestic-corgi.jpg", style:"width:50rem;border-radius:10px;display:block;margin-left:auto;margin-right:auto;width:75%;"%>
      </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "shiba_by_atrieisan.jpg", class:"d-block w-100", alt:"Majestic" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "prance-8.jpg", class:"d-block w-100", alt:"Shibe" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "wolves.jpg", class:"d-block w-100", alt:"Moon moons" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!--

<div class="jumbotron">
  <h1 class="display-4">Hey there!</h1>
  <p class="lead">Welcome to the much excellent blog. Blog of all blogs. Wow everyone and their mothers' socks off</p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-lg btn-outline-dark" href="<%= about_us_path %>" role="button">Learn more</a>
  </p>
</div> -->